### ISSUE TITLE
Exception handling in 20.1.0

### ISSUE THREAD

**Issue by ShirleyNekoDev** [hpi-swa/trufflesqueak#121]
When evaluating smalltalk files via Polyglot.evalFile('smalltalk', 'file.st') (in JavaScript ```polyglot --jvm main.js```), the execution fails with 
```
a UndeclaredVariableWarning @379ce046
        at <smalltalk> [] in UndefinedObject>>DoIt (offset: 4)(Unknown)
        at <smalltalk> BlockClosure>>cull:(BlockClosure>>cull::7:109-127)
        at <smalltalk> [] in Context>>handleSignal: (offset: 45)([] in Context>>handleSignal: (offset: 45):5:76-94)
        at <smalltalk> BlockClosure>>ensure:(BlockClosure>>ensure::3:44-77)
        at <smalltalk> Context>>handleSignal:(Context>>handleSignal::52:1179-1200)
        at <smalltalk> Context>>handleSignal:(Context>>handleSignal::26:533-560)
        at <smalltalk> Exception>>signal(Exception>>signal:7:140-166)
        at <smalltalk> Encoder>>undeclared:(Encoder>>undeclared::32:754-777)
        at <smalltalk> Parser>>correctVariable:interval:(Parser>>correctVariable:interval::42:969-994)
        at <smalltalk> [] in Parser>>variable (offset: 27)([] in Parser>>variable (offset: 27):6:87-125)
        at <smalltalk> [] in Encoder>>encodeVariable:sourceRange:ifUnknown: (offset: 12)([] in Encoder>>encodeVariable:sourceRange:ifUnknown: (offset: 12):17:415-433)
        at <smalltalk> Dictionary>>at:ifAbsent:(Dictionary>>at:ifAbsent::12:194-212)
        at <smalltalk> Encoder>>encodeVariable:sourceRange:ifUnknown:(Encoder>>encodeVariable:sourceRange:ifUnknown::28:711-737)
        at <smalltalk> Parser>>variable(Parser>>variable:30:647-701)
        at <smalltalk> Parser>>expression(Parser>>expression:13:241-263)
        at <smalltalk> Parser>>statements:innerBlock:blockNode:(Parser>>statements:innerBlock:blockNode::54:1260-1284)
        at <smalltalk> Parser>>statements:innerBlock:(Parser>>statements:innerBlock::6:110-158)
        at <smalltalk> Parser>>method:context:(Parser>>method:context::51:1076-1112)
        at <smalltalk> [] in Parser>>parseCue:noPattern:ifFail: (offset: 45)([] in Parser>>parseCue:noPattern:ifFail: (offset: 45):41:989-1019)
        at <smalltalk> BlockClosure>>on:do:(BlockClosure>>on:do::5:92-109)
        at <smalltalk> Parser>>parseCue:noPattern:ifFail:(Parser>>parseCue:noPattern:ifFail::111:3227-3249)
        at <smalltalk> Parser>>parse:class:noPattern:notifying:ifFail:(Parser>>parse:class:noPattern:notifying:ifFail::11:243-286)
        at <js> :program(main.js:2:30-70)
```
with 'file.st' containing only ```a := 0.```.

In version 20.0.0 this did not happen.
Calling 'file.st' directly via ```polyglot --jvm file.st``` does not show this problem.

As a fix for this problem I can declare the variable before assigning it (```|a|```).

**Comment by ShirleyNekoDev** [comment]
Another stacktrace after inserting the variable declaration:
```
a CurrentEnvironment @642505c7
        at <smalltalk> [] in UndefinedObject>>DoIt (offset: 4)(Unknown)
        at <smalltalk> BlockClosure>>cull:(BlockClosure>>cull::7:109-127)
        at <smalltalk> [] in Context>>handleSignal: (offset: 45)([] in Context>>handleSignal: (offset: 45):5:76-94)
        at <smalltalk> BlockClosure>>ensure:(BlockClosure>>ensure::3:44-77)
        at <smalltalk> Context>>handleSignal:(Context>>handleSignal::52:1179-1200)
        at <smalltalk> Exception>>signal(Exception>>signal:7:140-166)
        at <smalltalk> Exception class>>signal(Exception class>>signal:3:29-48)
        at <smalltalk> ClassBuilder>>superclass:subclass:instanceVariableNames:classVariableNames:poolDictionaries:category:(ClassBuilder>>superclass:subclass:instanceVariableNames:classVariableNames:poolDictionaries:category::2:61-80)
        at <smalltalk> Class>>subclass:instanceVariableNames:classVariableNames:poolDictionaries:category:(Class>>subclass:instanceVariableNames:classVariableNames:poolDictionaries:category::9:173-276)
        at <smalltalk> CTX UndefinedObject>>DoIt @6428591a(UndefinedObject>>DoIt:11:308-401)
        at <js> :program([...]Controller.js:1:27-71)
        at <js> :program(main.js:5:113-167)
```

Inside a JS file after polyglot eval of smalltalk.

**Comment by fniephaus** [comment]
Closed via https://github.com/hpi-swa/trufflesqueak/commit/db406532e10bd96ea0efe39eab92cc6417a73b70.
