### ISSUE TITLE
TruffleSqueak failed to launch Squeak6.0beta-21772 image

### ISSUE THREAD

**Issue by dram** [hpi-swa/trufflesqueak#156]
Following error will be occurred when trying to launch Squeak6.0beta-21772 image in TruffleSqueak 22.1.0:

```
[trufflesqueak] Running Squeak6.0beta-21772-64bit.image on GraalVM CE (latency mode)...
== Truffle stack trace ===========================================================
Image format 68533 not supported. Please supply a 64bit Spur image (format 68021).
        at <smalltalk> null(Unknown)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:399)
        at de.hpi.swa.trufflesqueak.launcher.TruffleSqueakLauncher.execute(TruffleSqueakLauncher.java:126)
        at de.hpi.swa.trufflesqueak.launcher.TruffleSqueakLauncher.launch(TruffleSqueakLauncher.java:82)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
        at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
        at org.graalvm.launcher.AbstractLanguageLauncher.runLauncher(AbstractLanguageLauncher.java:168)
```

Which seems to be related to https://lists.squeakfoundation.org/pipermail/squeak-dev/2022-May/220659.html

**Comment by fniephaus** [comment]
Thanks for raising this and for the pointer, @dram. I've just pushed a fix for this to the `main` branch so support for images with the `68533` format will ship with the next release.

**Comment by dram** [comment]
Fix confirmed, thanks!
