### ISSUE TITLE
Network unavailable

### ISSUE THREAD

**Issue by psvensson** [hpi-swa/trufflesqueak#170]
I've donlnoaded and started the latest version (TruffleSqueak-22.1.0.image) running under GraalVm for OpenJDk 17 on Linux Mint 20.2.

It starts fine and I can run som eexamples, but as soon as I try to do anything involving the network (like starting a monitcello installer), the image hangs and eventually produces a debugger where it's obvious that the result was nil.

**Comment by fniephaus** [comment]
Hi @psvensson, thanks for raising this. Unfortunately, TruffleSqueak's implementation of the SocketPlugin is currently incomplete and still has a few issues, so it is not surprising that some networking tasks fail. The problem is that we're emulating what the SocketPlugin does using [Java NIO](https://github.com/hpi-swa/trufflesqueak/pull/21) and that's not always working.

Ultimately, it would be nice to implement the SocketPlugin based on a POSIX backend, similar to GraalPython (https://github.com/hpi-swa/trufflesqueak/issues/39#issuecomment-1134566709).

**Comment by psvensson** [comment]
Hi Fabio, thanks for the quick reply. OK, but then it is a  known issue and you also know where it can be fixed. I know a bit of Smalltalk and a bit of Java, but not much about GraalVM or indeed truffleSqueak. I will probably fail but will see what I can do :) 

I do not know Python so would start to see if I could find a good enough solution fixing existing bugs / implementing what needs to implemented.

I assume that I start looking here; https://github.com/hpi-swa/trufflesqueak/tree/main/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/nodes/plugins/network

Do you have any more hints or ideas on how to go about this, obvious shortlist of what is not working or something like that?

**Comment by fniephaus** [comment]
Yes, it is a known issue. It just never was pressing enough to fix because, well, you can do networking via interop with Ruby or other programming languages. :wink:

I don't think you need to know much about Python. GraalPython is, just like TruffleSqueak, implemented in Java using Truffle.
What you could do is copy over the [`PosixSupportLibrary`](https://github.com/oracle/graalpython/blob/f086f809b46041d325d3814cced61f36371de84d/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/PosixSupportLibrary.java) and its implementations (e.g., [`NFIPosixSupport`](https://github.com/oracle/graalpython/blob/f086f809b46041d325d3814cced61f36371de84d/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/NFIPosixSupport.java) and/or [`EmulatedPosixSupport`](https://github.com/oracle/graalpython/blob/f086f809b46041d325d3814cced61f36371de84d/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/EmulatedPosixSupport.java)) and re-implement the SocketPlugin primitives.

An example:
`primitiveResolverGetAddressInfo` is currently not implemented, I think, and uses `getaddrinfo` under the hood in the OpenSmalltalkVM ([here's `primitiveResolverGetAddressInfo`](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/f6594056fa5de7709b67e323877ff8d1d7de573a/src/plugins/SocketPlugin/SocketPlugin.c#L336) and [here's the getaddrinfo() call in the Unix impl.](https://github.com/OpenSmalltalk/opensmalltalk-vm/blob/144607df34b6653436907470ae313155e942f883/platforms/unix/plugins/SocketPlugin/sqUnixSocket.c#L1824)). So in TruffleSqueak, the primitive could be implemented using [`getaddrinfo` from the POSIX backend](https://github.com/oracle/graalpython/blob/f086f809b46041d325d3814cced61f36371de84d/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/PosixSupportLibrary.java#L701). If you have troubles doing that, you could copy over just the [`getaddrinfo` impl from the EmulatedPosixBackend](https://github.com/oracle/graalpython/blob/f086f809b46041d325d3814cced61f36371de84d/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/runtime/EmulatedPosixSupport.java#L2871-L2965) and use that to implement `primitiveResolverGetAddressInfo`.

One more tip: If you select the TruffleSqueak test image the first time you start TruffleSqueak, you can also look at the original Slang sources of the SocketPlugin, which may be helpful as well.

I don't want to discourage you in any way but I think it's fair to warn you that this is not really a beginner project. Please feel free to give it a shot and asked questions!

**Comment by psvensson** [comment]
Just thought I could post my proceedings here, for reference.

I have been bale to compile from command-line both GraalVM and truffleSqueak according to instructions, using the proper JVM downloaded by mx.

It then did prove possible to connect eclipse as a remote debugger (using an already defined target for this - thanks) to connect to a truffleSqueak instance using according to the development instructions. I then set a lot of breakpoints in SqueakSocket.java and SqueakTCPSocket.java.

It turns out that name resolution works well, I'm able to set breakpoints in SqueackTCPSocket::receiveDataFrom where an address is present.

But there things are stuck and I'm trying to figure out why. It feels like receive never returns, and then eventually it times out and truffleSqueak gets back nil and throws an exception. The odd hting is that I can see that data is received, and follow it a couple of times. I'm still trying to get to grips with Eclipse deugging again, but I'm fairly sure that something comes across.

![trufflesqueak_net_debug_2_ 2022-07-09 09-46-51](https://user-images.githubusercontent.com/39554/178097256-b2758136-369d-4a64-b322-25af3d591dd6.png)

**Comment by psvensson** [comment]
Hmm, I might juts as well have started properly inside truffleSqueak, though, as when I look more closely, it does actually receive data, the main problem seems to be that the connection is closed before data is fully read, or that it thinks so.

It might be that some parts of the TCP plugin does not handle the final part of data being received and/or explicitly close the connection beforehand.

![trufflesqueak_debug_net_3 2022-07-09 11-31-50](https://user-images.githubusercontent.com/39554/178100244-dfec5ecf-39c1-40a5-a76e-8e0d7575941a.png)

**Comment by fniephaus** [comment]
Great that you're able to dive into networking in TruffleSqueak!

I remember that there are some issues with certain websites. I just had a quick look and the non-SSL version of the website seems to work fine (`WebClient httpGet: 'http://dn.se'`). Maybe this has also something to do with the `SqueakSSL` plugin?

In case you only need to send some simple http requests, you can also implement a subclass of `WebClient` using Java, Python, Ruby, or some other GraalVM language.

**Comment by psvensson** [comment]
Ahaa, good catch! yes, this seems to be just about https indeed. It might be SqueakSSL, but I also saw some comments in the SecureSocketStream, which says:

```"Note: The loop here is necessary to catch cases where a TLS packet is
	split among TCP packets. In this case we would pull the first portion of
	the TLS packet here but receiveAvailableData would return nothing since
	the contents of the packet can't be decoded until the rest has come in."```

So I'll check that out first. It feels like that for SSL, something thinks there is data to be read when it really isn't any, so I hoe to narrow down where soon.

And yes, I could call out to node.js for example, but my goal is to see if it would be possible to lift truffleSqueak to a level where it's more or less as usable as the standard distribution, but with ultra-mega-superpowers. So I'll continue to weld here in the cellar for a while longer :)

**Comment by psvensson** [comment]
Silly question, but what is the easiest way to get some logging output from the Java/vm code? I tried something like this;

protected final boolean isDataAvailable() throws IOException {
        selector.selectNow();
        final Set<SelectionKey> keys = selector.selectedKeys();
        System.out.println("isDataAvailable keys length = " + keys.size());
        for (final SelectionKey key : keys) {
            if (key.isReadable()) {
                LogUtils.SOCKET.finer(() -> this + " data available");
                return true;
            }
        }

        LogUtils.SOCKET.finer(() -> this + " no data available");
        return false;
    }

And checked bout stdout and the console tab in Eclipse so of course nothing showed (but it does get called, I can set a breakpoint there, for example). 

Since data transport function get called many times, debugging doesn't give the whole picture I need to see where things go awry, so I do need a way to print things over time. In Squeak land Transcript works well as usual, of course.

There are also logging options to set for the vm when starting it, but I don't understand what to write here;
From the help:

--log.[logger].level=<String>                Set language log level to OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST or ALL

What are possible values of [logger] here?

**Comment by fniephaus** [comment]
Not a silly question at all, looks like we haven't documented this yet. You've seen the [list of loggers](https://github.com/hpi-swa/trufflesqueak/blob/c99d6f23329a9d09a3c3a03c4442c57bd20ffc31/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/util/LogUtils.java#L20-L29), and the way you use enable is like this:

```bash
# enable only the socket logger on the FINER level
trufflesqueak --log.smalltalk.socket.level=FINER
# enable all loggers at the same time on the ALL level (this is very verbose)
trufflesqueak --log.smalltalk.level=ALL
```

**Comment by psvensson** [comment]
Thanks! 
OK, hmm. I do not see any output anywhere when I do that (even with the ALL option). 

Also, I tried to do --log.java.level=ALL but nothing happened with that either. It sounded like it should work and I am 100% for this, but more magic is needed, apparently

**Comment by psvensson** [comment]
For the ongoing research I'm now fairly convinced that the culprit is the SqueakSocket::isDataAvailable method in teh plugin, which I think does not flag that data is available when it is.

**Comment by fniephaus** [comment]
Can you check that `--log.smalltalk.primitives.level=ALL` or some other logger works for you? Are you sure you're running the code that you are seeing? It's sometimes easy to forget to rebuild with `mx`.

BTW, I recommend something like this:
```
cd trufflesqueak
mx --dy /compiler build # build TruffleSqueak and Graal compiler
../graal/sdk/latest_graalvm_home/bin/trufflesqueak # always points to the latest TruffleSqueak build
# change TruffleSqueak code...
mx --dy /compiler build # should rebuild only TruffleSqueak
../graal/sdk/latest_graalvm_home/bin/trufflesqueak --log.smalltalk.socket.level=FINER
```

Bonus points for setting `$GRAALVM_HOME` to your `/path/to/graal/sdk/latest_graalvm_home`, which allows you to use this instead:
```
$GRAALVM_HOME/bin/trufflesqueak --log.smalltalk.socket.level=FINER
```

**Comment by fniephaus** [comment]
and this would let you run with the Java debugger:
```
$GRAALVM_HOME/bin/trufflesqueak --vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y
```

**Comment by psvensson** [comment]
Aha!  Wow, of course. I had all the time happily just started trufflesqueak without specifying which one, so of course I ran the earlier installation of trufflesqueak in my classpath from when I downloaded it while trying things out.

Now, when I correctly start using the following line;

 `$GRAALVM_HOME/bin/trufflesqueak --vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y ../../../Installs/graalvm-ce-java17-22.1.0/languages/smalltalk/resources/TruffleSqueakTestImage-6.0alpha-20288b-64bit.image --log.smalltalk.socket.level=FINER`

I do see a lot of logging, including my System.out.println. Thank you, the car is moving again :)

**Comment by psvensson** [comment]
However, now that am using the correct and locally built truffleSqueak, I am starting to see a lot of DNUs for getLoopAndCount .
![image](https://user-images.githubusercontent.com/39554/178151159-6f5b60ad-ea5c-4aa6-9ca9-e5355ea6f13a.png)

They appear after I've get the usual exception on not being able to go to the https site, and after that appear every time I try to do anything with a calltarget browser (like looking at any code, so I then need to restart again. Any ideas what it might be?

**Comment by fniephaus** [comment]
It seems like you're using the `CallTargetBrowser` without [opening the right modules for allow for introspection](https://github.com/hpi-swa/trufflesqueak/blob/c99d6f23329a9d09a3c3a03c4442c57bd20ffc31/mx.trufflesqueak/launchers/trufflesqueak#L15-L24). Note that this also only works when running with the Graal compiler.

If you don't need to use the CallTargetBrowser, I suggest you switch back to the standard Browser via, for example, `SystemBrowser askForDefault` and then pick "Browser".

**Comment by psvensson** [comment]
Thanks a lot for the help

**Comment by psvensson** [comment]
I have now run into another problem which is very confusing. I merely made the suggested changes (and changed browser), saved the image and then restarted. Now, after I start truffleSqueak and then tries to attach the Eclipse debugger, I get this; 

```
$ $GRAALVM_HOME/bin/trufflesqueak --vm.Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y ../../../Installs/graalvm-ce-java17-22.1.0/languages/smalltalk/resources/TruffleSqueakTestImage-6.0alpha-20288b-64bit.image --log.smalltalk.level=FINER
WARNING: Unknown module: jdk.internal.vm.compiler specified to --add-opens
Listening for transport dt_socket at address: 8000
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
[trufflesqueak] Running TruffleSqueakTestImage-6.0alpha-20288b-64bit.image on Interpreted...
ERROR: java.lang.NullPointerException: Cannot invoke "de.hpi.swa.trufflesqueak.image.SqueakImageChunk.setObject(Object)" because "specialChunk" is null
org.graalvm.polyglot.PolyglotException: java.lang.NullPointerException: Cannot invoke "de.hpi.swa.trufflesqueak.image.SqueakImageChunk.setObject(Object)" because "specialChunk" is null
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.initPrebuiltConstant(SqueakImageReader.java:303)
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.initObjects(SqueakImageReader.java:354)
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.run(SqueakImageReader.java:90)
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.load(SqueakImageReader.java:75)
	at de.hpi.swa.trufflesqueak.SqueakImage$SqueakImageNode.execute(SqueakImage.java:40)
	at <smalltalk> null(Unknown)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:399)
	at de.hpi.swa.trufflesqueak.launcher.TruffleSqueakLauncher.execute(TruffleSqueakLauncher.java:126)
	at de.hpi.swa.trufflesqueak.launcher.TruffleSqueakLauncher.launch(TruffleSqueakLauncher.java:82)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.runLauncher(AbstractLanguageLauncher.java:168)
Original Internal Error: 
java.lang.NullPointerException: Cannot invoke "de.hpi.swa.trufflesqueak.image.SqueakImageChunk.setObject(Object)" because "specialChunk" is null
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.initPrebuiltConstant(SqueakImageReader.java:303)
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.initObjects(SqueakImageReader.java:354)
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.run(SqueakImageReader.java:90)
	at de.hpi.swa.trufflesqueak.image.SqueakImageReader.load(SqueakImageReader.java:75)
	at de.hpi.swa.trufflesqueak.SqueakImage$SqueakImageNode.execute(SqueakImage.java:40)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.callDirectOrIndirect(DefaultCallTarget.java:85)
	at org.graalvm.truffle/com.oracle.truffle.api.impl.DefaultCallTarget.call(DefaultCallTarget.java:102)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1326)
	at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
	at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:399)
	at de.hpi.swa.trufflesqueak.launcher.TruffleSqueakLauncher.execute(TruffleSqueakLauncher.java:126)
	at de.hpi.swa.trufflesqueak.launcher.TruffleSqueakLauncher.launch(TruffleSqueakLauncher.java:82)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:296)
	at org.graalvm.launcher.AbstractLanguageLauncher.launch(AbstractLanguageLauncher.java:121)
	at org.graalvm.launcher.AbstractLanguageLauncher.runLauncher(AbstractLanguageLauncher.java:168)
Caused by: Attached Guest Language Frames (1)

```
I have tried to rebuild the truffleSqueak vm and then all of it, but to no avail. I then thought that the changes file of the image might have been damaged (maybe I terminated it too soon?) so I removed it and tried again, but got the same thing again.

It is very strange, I have not had time to do anything in particular (what I can remember). Is this something you have come across before?

As a last resort I'll download everything again and begin from scratch.

**Comment by fniephaus** [comment]
It seems the image has been damanged somehow. I believe the first positional argument is the image and all following are considered image arguments. So to avoid confusion, I'd either move the log option before the image file or drop the image argument. If no image is provided, TruffleSqueak will automatically use the one in the resources directory.

To get a fresh test image, simply empty "Installs/graalvm-ce-java17-22.1.0/languages/smalltalk/resources/" and run TruffleSqueak again. It should asked you again to select an image.

**Comment by psvensson** [comment]
Thank you, that did the trick.

**Comment by psvensson** [comment]
Some observations while spelunking the code;
1. When rebuilding the truffleSqueak VM, the donwloaded image gets (understandaböe) deleted and must be donwloaded anew.
2. It is only the 'test' image (option 2) which has logging enabled, so trying to set logging to anything at all while using (for example) the recommended image does not work.
3. Copying a donwloaded squeak image to a safe location and using the when starting truffleSqueak for debugging is not quite enough, since it then complains that it cannot find its sources

![image](https://user-images.githubusercontent.com/39554/178241821-7d02036e-9905-41ea-8ca8-7230339a22c3.png)

This just in case anyone else stumbles on the same things in the future :) 

The Graal socket python code is not like the smalltalk one, so they don't compare directly. But it's very little code in both cases. The problem arises when in the SecureSocketStream tries to read further from the socket but is blocked until timeout. It reads initial data but then in a subsequent step just sits there.

It has to be an assumption on what the underlying layer should do, or not, but it is not very obvious (yet) what it is. I'm reading up on java.nio and getting my bearings.

Will be travelling for a couple of days now, so getting back to this later in the week.

**Comment by fniephaus** [comment]
Good find, that is indeed interesting! And enjoy your vacation! I'm currently occupied with some other things anyway until the end of next week, but it'd be great to fix this at some point and happy to help as much as my time allows.

**Comment by psvensson** [comment]
Since the truffleSqueak SockePlugin obviously works in some cases, I have been trying to find the difference in handling from the SqueakSSL side between going directly to https and being redirected to https. I had several great theories, but none stuck unfortunately.

I now tried other sites than the one I've been testing, and interesting things happens.

vanilla http request `WebClient httpGet: 'http://google.com'` fails silently with a Transcript complaint of 'Unknown cookie field: SameSite' after redirecting from google.com to www.google.com. 

On the other had, going directly to https to github; `WebClient httpGet: 'https://github.com'` works!

The only reason I can think of is that it is the WebClient which is wonky.

Trying to update Squeak fails happily as usual, trying to access `http://source.squeak.org/trunk` which is just http:// and accessible through a browser.

it might be that it is the WebClient which is not correctly hotted-up to dance the latest dances? However, that can't be true since it does actually work in a vanilla VM squeak 6.0.

Very X-files right now :)

**Comment by fniephaus** [comment]
TruffleSqueak's image and test image are based on a fixed Squeak trunk image that we haven't updated in a while. So maybe worth doing these experiments in a Squeak 6.0 release image since `WebClient` might have seen some updates?

**Comment by psvensson** [comment]
Yes, that is a good idea. Actually, I was wondering how to create new truffleSqueak images and a bit about how one would go about to write the Smalltalk parts (if needed) to get truffleSqueak to work with another Smalltalk (I was thinking Pharo, for example).
If you could add some notes on that to the docs that would be great. And then I could also help out more

**Comment by psvensson** [comment]
Thank you, of course i was already documented, sry :) I'll give it a try and see if anything have changed in WebClient to the better.
Also, I will of course ask in the GraalVM channels on how to install gu - still mixing projects, it seems

**Comment by psvensson** [comment]
The first parts of the setup image instructions went well, but when executing the last 'setupImage' part,

`(Smalltalk at: #TruffleSqueakUtilities) setUpImage.`

 I get this exception
![image](https://user-images.githubusercontent.com/39554/179006756-fdc6f6b4-8599-4d1d-81cc-3a2ad7a11986.png)

**Comment by fniephaus** [comment]
> Thank you, of course i was already documented, sry :) I'll give it a try and see if anything have changed in WebClient to the better.
Also, I will of course ask in the GraalVM channels on how to install gu - still mixing projects, it seems

There's also a `#trufflesqueak` channel in the [GraalVM Slack](https://www.graalvm.org/slack-invitation/) where you can reach me.

> The first parts of the setup image instructions went well, but when executing the last 'setupImage' part,
(Smalltalk at: #TruffleSqueakUtilities) setUpImage.
I get this exception

I'm not surprised, but this is not too much of a problem because it's setting up some workspace or something. Try running the TruffleSqueak tests, that'd be interesting.

**Comment by psvensson** [comment]
This is excellent stuff! Could you please add this to the existing documentation, I think it would be really helpful to have it all in one place (and so one can search for it also).

OK, now I need to make a choice hmmm :)

**Comment by psvensson** [comment]
NP, I'll make a small PR of an edited version of your text, to the development documentation

**Comment by psvensson** [comment]
So, hmm. I have had a bout of Covid so been under the ice for most of the week. But today I managed to fix the trufflesqueak setup utilities to work with the actual squeak 6.0 release. They have made several changes that are probably nice but completely ignores backward compatibility. It almost feels like a Pharo core dev have been working with this :) .

This fix might not be ideal, but I crated a PR for the 'image' branch and we can crate a new issue if/when you want to have any changes done to it.

Anyhow, after I got the setup working, I again tried to do the very first WebClient test that is the reason for this issue in the first place -- and it worked. Of course it now worked.

![image](https://user-images.githubusercontent.com/39554/180651461-707a677e-53e8-47c4-8d0a-26316fd10242.png)

So the problem was indeed some weird bug in the WebClient handling of SqueakSSL which was fixed between the release used in the TruffleSqueak documentation and the official release - I don't even want to go back and find out what it was, but now it runs and purrs.

**Comment by fniephaus** [comment]
> So, hmm. I have had a bout of Covid so been under the ice for most of the week.

Oh, I hope you are better now! Thanks for the PR!

> Of course it now worked.

That's great news, thanks for checking! According to the [Squeak/Smalltalk 6.0 release notes](https://raw.githubusercontent.com/squeak-smalltalk/squeak-app/squeak-trunk/release-notes/6.0), `WebClient` has received some bug fixes and improvements... always good if the problem turned out to be fixed somewhere else. :)

We'll upgrade to the 6.0 release image very soon (after the upcoming 22.2 release), but that will mean that the new 6.0-based image will ship with TruffleSqueak 22.3 in a couple of months (we'll need some time to make sure everything's working ok).

**Comment by psvensson** [comment]
I am, thanks! Yes, this has been a bit of a surprising ride, but it all ended well.
Please let me know if there is anything else you need from me to close this ticket. And also looking forward to any changes need to the image PR. I haven't looked at everything so I don't feel I have the full picture

**Comment by fniephaus** [comment]
Good! I'm keeping this open until we've adopted the 6.0 release. The most work is going to be updating the test map in [`test.properties`](https://github.com/hpi-swa/trufflesqueak/blob/bcfb6ce4abe2ffae760c03d19a4ffa09903500ad/src/de.hpi.swa.trufflesqueak.test/src/de/hpi/swa/trufflesqueak/test/tests.properties). [`testTestMapConsistency`](https://github.com/hpi-swa/trufflesqueak/blob/a289d9d8d607c01e81d0082ea90614ec36565c6a/src/TruffleSqueak-Tests.package/TruffleSqueakTest.class/instance/testTestMapConsistency.st) is the test for this. I'm sure there are many new tests and some test removals. And then, we need to figure out which ones work and which ones don't.

**Comment by psvensson** [comment]
OK, sounds good! I'll lick my wounds a bit until the next release then. I also had some problems using a recent dev graalVm , this dev truffleSqueak and adding node.js. Also I could not figure out a way to list the installed languages in truffleSqueak in a printable format. All I got was just remote objects. I suspect this is just a bit of missing docs (or me not finding it) but we can take that later then. Very glad we got this far.

**Comment by fniephaus** [comment]
Sure, let me know in case you run into problems and don't know how to proceed. For language names, you can, for example, do this: `Polyglot availableLanguages collect: [ :ea | ea getName asString ]`.

**Comment by psvensson** [comment]
OK, I will try this, thx

**Comment by psvensson** [comment]
So, this is embarrassing. I have had fevers on and off and it's sometimes easy to mix things up.

The image I tested was indeed the latest 6.0 release - but it was running on a standard VM. I had just started it some days earlier trying to debug the trufflesqueak image setup process.

So o course the (now also fixed) WebClient worked when I tried it.

Now I saved the image and restarted it under my latest GraalVM/Trufflesqueak installation, and it sadly show the same problems as before - unable to read more than an initial amount from a https url, but works well when using http which redirects to https.

**Comment by fniephaus** [comment]
> I have had fevers on and off and it's sometimes easy to mix things up.

I hope you are feeling better now!

> it sadly show the same problems

Ok, so this issue is essential still a problem?

**Comment by psvensson** [comment]
A little bit, thank you. 

Yes, it seems so, unfortunately. 

I will try out Cuis as well (and Maybe Pharo) to see if I can get something out of that. Also, I'll start checking out how the open smalltalk VM implements things, in case something pops out.

**Comment by psvensson** [comment]
Cuis seems to have the same issue, but behaves a little bit differently. It doesn't time out after 45s but instead throws an exception when the remote side closes the connection.

![image](https://user-images.githubusercontent.com/39554/180795685-b918b299-a044-4d8c-88ad-e795e6190c90.png)

I am trying to understand what needs to be installed in Pharo to make it work over truffleSqueak but I'm stuck trying to figure out how the Cuis image setup works and what it is doing; https://github.com/hpi-swa/trufflesqueak/blob/main/docs/images.md#trufflesqueak-image-creation 

I did look quickly at the squeak baseline for trufflesqueak and that of course does not work with Pharo, but perhaps it would be possible to modify it a little bit so it can detect Pharo and do something else instead.

**Comment by fniephaus** [comment]
Interesting, maybe the `SqueakSSL` plugin in TruffleSqueak doesn't claim to be done early enough and leaves the connection open.

As mentioned in https://github.com/hpi-swa/trufflesqueak/issues/170#issuecomment-1184450457, Pharo isn't as easy to support as Cuis and probably requires significantly more work than needed to fix the `SqueakSSL` plugin.

**Comment by psvensson** [comment]
Yes, that could be the case.

Hmm, yes. You know that much more than I do of course, but it seems to be the need for filesystem access in the editor and should be not too difficult if so.

The reason Pharo is interesting is that is has its very own web client, as part of the Zinc Web server/client package by Sven von Caekenberg, so it would have provided an excellent triangulation vs. the Squeak and Cuis WebClient.

But OK, I'll start comparing the open smalltalk vm SSL plugin and see what I can find. Will probably be some time.

**Comment by fniephaus** [comment]
So I had some time to look into this myself. I logged a couple of things inside the image and found out that the connect primitive never returns `-1`, which signals that "More input is required". So I digged into the [SqueakSSL code](https://github.com/squeak-smalltalk/squeakssl/) and [found where](https://github.com/squeak-smalltalk/squeakssl/blob/5294be440b0535dd11648d6c041245e53f8fa388/src/unix/sqUnixOpenSSL.c#L539) it is supposed to ask for more input.

With https://github.com/hpi-swa/trufflesqueak/commit/f44be51cbe11df2451d8d94c579aeb93c84fd8a9, `WebClient httpGet: 'https://dn.se'` and `WebClient httpGet: 'https://google.com'` now work for me. However, I think some of the `SqueakSSLTest` cases are failing now, maybe they never really succeeded. I don't know yet...

**Comment by psvensson** [comment]
Thank you! This is awesome. Is there anything else, maybe a bit higher-level that I could help out with?

**Comment by fniephaus** [comment]
Loading the TruffleSqueak image into Cuis is still on the [todo list for Cuis support](https://github.com/hpi-swa/trufflesqueak/issues/154#issue-1112950057). I'm not sure that the tools work (e.g., polyglot workspace), but the core package should. I also noticed some input issues (e.g., in Cuis or #160). That should be relatively easy to fix, you can find mouse and keyboard classes in [here](https://github.com/hpi-swa/trufflesqueak/tree/23e54fbbbe3738d48eb93086ee4d21643c835caa/src/de.hpi.swa.trufflesqueak/src/de/hpi/swa/trufflesqueak/io).

Otherwise, feel free to build a tool or polyglot application in TruffleSqueak. I'm always curious to see what others build with it :)

**Comment by psvensson** [comment]
Alright, I'll do some exploring loading the TruffleSquek core stuff in Cuis and report back in that ticket.

But actually building on top of TruffleSqueak is what I came for :) I have a quite promising idea for cloud deployment that should be applicable to any cloud provider, but where I'm constantly hampered by lack of library support (gRPC, for example), so my immediate goal is to see if I can leverage node.js to this end.

The interesting part then is how to make sure that Baselines work with/maps automagically to (for example) npm, so that polyglot dependencies can be handled in a (hopefully) generic way.

**Comment by fniephaus** [comment]
Dependency management for polyglot applications is definitely an interesting topic!

Please note though that Node.js is usually not exposed as a polyglot language directly. You can call out to Smalltalk from within GraalVM's Node.js runtime, but I don't think you can use the programming system then. You may want to have a look at [NodeJVM](https://github.com/mikehearn/nodejvm) although it's a bit dated.

**Comment by psvensson** [comment]
OK, I'm not sure I understand. Wouldn't I be able to install node.js as a graalvm language, so it would be available symmetrically to smalltalk and (let's say) python?

**Comment by fniephaus** [comment]
> Wouldn't I be able to install node.js as a graalvm language

Yes, that's correct. The problem is that Node.js is a framework built on top of JavaScript. While you can interop with JavaScript, GraalVM doesn't allow you to interop with Node.js, e.g., using npm packages. I'm still hoping this will be supported at some point, but it's a bit tricky because apparently, Node.js has its own main loop.

**Comment by psvensson** [comment]
Cuis is quite very much different when it comes to code loading. I think I withdraw my offer for now :) Maybe better to focus on learning how to do polyglot stuff in a more narrow context first.

When reading the graal node.js documentation I had hoped that it would be possible to use node.js full-out. And I assume that it is possible if you start out with node. Graal can run node.js and npm t.c.  but when polyglot calling out to node.js this does not hold, have I understood it properly?

In that case, the node.js polyglot support seems currently to be be not of very much use, since just evaluating JS will not go very far. 

Hmmm, but wouldn't the grallvm node.js module be that thread? The use-case I'm thinking of hear is that of calling out from languag a (Smalltalk, of course) to language b (js/node.js) and loading and then executin code in a npm package.

Hmmmmm.. perhaps the problem resides in node.js wonky package loading, which was staunchly blocking for many years and which need to make use of its own thread. In recent years, the common js way of loading have started to be supported, so perhaps if one loaded packages *in the right way* it might work. 

I think I'll start to ask adjacent questions like this in the slack channel instead so as not pollute further this issue :)
