### ISSUE TITLE
BufferOverflowException in SqueakSSL plugin

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/trufflesqueak#92]
### Repro do-It
```smalltalk
WebClient httpGet: 'https://upload.wikimedia.org/wikipedia/en/e/ef/Commander_Keen_cover_art.jpeg'.
```

### Stack trace
```
java.nio.BufferOverflowException
	at java.nio.HeapByteBuffer.put(HeapByteBuffer.java:206)
	at de.hpi.swa.graal.squeak.nodes.plugins.SqueakSSL$PrimDecryptNode.doDecrypt(SqueakSSL.java:688)
	at de.hpi.swa.graal.squeak.nodes.plugins.SqueakSSLFactory$PrimDecryptNodeFactory$PrimDecryptNodeGen.executeWithArguments(SqueakSSLFactory.java:489)
...
```

Tested with GraalSqueak `1.0.0-rc6` (fb5f87b4045b05c964aae32526f2dded420c1d66) and GraalVM CE `19.3`.

**Comment by fniephaus** [comment]
With https://github.com/hpi-swa/trufflesqueak/commit/65f683a301d8ecbcd0f01ca1205c0be1aa330b9f, the repro works fine on macOS. It's possible that the `BufferOverflowException` happens on Linux only.

**Comment by fniephaus** [comment]
#110 looks like another problem. I'm going to close this one for now.
